name: Build fdroid APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v3

# Runs a single command using the runners shell
    - name: Create Docker container
      run: docker build . --file Dockerfile --tag tailscale-android

    # Runs a set of commands using the runners shell
    - name: build tailscale-fdroid.apk
      run: docker run -v /home/runner/work/tailscale-android/tailscale-android:/build/tailscale-android tailscale-android make tailscale-fdroid.apk 

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        # Artifact name
        name: tailscale-fdroid.apk # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: /home/runner/work/tailscale-android/tailscale-android/tailscale-fdroid.apk
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error # optional, default is warn


        retention-days: 30 # optional
